### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by mamayuan**
Added more tests to increase test coverage

### CODE REVIEW

**Comment by Cloud7050** [comment]
>Merging ... will not change coverage.

Huh?

**Comment by Cloud7050** [comment]
Also works towards #184.

**Comment by rayshawntan** [comment]
I think codecov did not increase cause these are codes that already have been tested

**Comment by mamayuan** [comment]
> I think codecov did not increase cause these are codes that already have been tested

That was unexpected... I guess the tests I added are more of special cases of existing tests...

**Review by Cloud7050 — APPROVED** [review]

**Review by rayshawntan — APPROVED** [review]

**Pull request merged**
