### PR TITLE
Better explanation on whether Index is zero/one-based

### LINKED ISSUE #172: [PE-D][Tester D] Better explanation on whether Index is zero/one-based.
Better explanation on whether the INDEX provided in commands are zero/one-indexed. 

For a computer science student, he/she may think that the first index starts from zero. Therefore, even when receiving the error message, it doesn't aid him in understanding what index he should input.

Perhaps, one improvement is to better specify in the error message for the user to start from 1 till end of file.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: sheryew/ped#6

### PR DESCRIPTION
**Pull request by bwangpj**
Update UG to explain 1-indexing. 

Closes #172.

### CODE REVIEW

**Review by mamayuan — COMMENTED** [review]
I feel like we don’t need to repeat about it. Repetition can also be penalized.

**Comment by bwangpj** [comment]
> I feel like we don’t need to repeat about it. Repetition can also be penalized.

Yep ok, updated

**Comment by rayshawntan** [comment]
I think instead of removing the line entirely, it could be possible to instead ask user to refer to the edit line instead about indexing, similar to how the other sections have references to parts above.

**Comment by bwangpj** [comment]
> I think instead of removing the line entirely, it could be possible to instead ask user to refer to the edit line instead about indexing, similar to how the other sections have references to parts above.

I thought of doing that, but then I realised actually it already says that just after the `Format:`

**Review by rayshawntan — APPROVED** [review]

**Review by Cloud7050 — APPROVED** [review]

**Pull request merged**
