### PR TITLE
[Week 10] Add mass delete feature

### LINKED ISSUE #103: Add new feature MassDelete
Allow the user to delete multiple contacts based on index at once.

### PR DESCRIPTION
**Pull request by mamayuan**
Added mass delete feature with tests. Updated User Guide and Developer Guide regarding current delete command.

Closes #103

### CODE REVIEW

**Review by rayshawntan — COMMENTED** [review]
I think DG requires the implementation part as well.

**Comment by rayshawntan** [comment]
> > I think DG requires the implementation part as well.
> 
> You mean to include the diagrams also?

Yea, the same area as where I did my implementation for features.

**Comment by mamayuan** [comment]
> > > I think DG requires the implementation part as well.
> > 
> > 
> > You mean to include the diagrams also?
> 
> Yea, the same area as where I did my implementation for features.

OK. But I dont think I have time to finish before the deadline tmr. I'll complete that in a separate PR this weekend. Could you review what I currently have just for this PR? Thanks!

**Review by bwangpj — APPROVED** [review]
Approved for dashboard purposes but same comment as @rayshawntan above

**Review by rayshawntan — APPROVED** [review]

**Pull request merged**
