### PR TITLE
[Week 8] Combine test Person data

### LINKED ISSUE #27: Combine test Person data
The test code was contributed to by many people many years ago and was changed over time. There appears to be at least two different styles of creating test Persons that got partially merged together somewhere down the line (see `TypicalPersons.java` "Manually added" and `CommandTestUtil.java`).

Let's make this consistent and simpler (ie easier to work with) by replacing these. We could define some kind of nested static classes in `testutil/` to serve as the single source of all our test data strings - both valid and invalid.

Once complete, an example of consuming such data would be `INPUT.VALID.NAME.AMY_WHITESPACE` for a string something like `   Amy Bee   `. That way, we won't have a mix of valid and invalid strings scattered all throughout the test code, yet at the same time have some strings stored elsewhere and used via static imports.

### PR DESCRIPTION
**Pull request by rayshawntan**
Shift all test data into `TestData.java` for easier readability for future updates of test cases. 

Closes #27.

### CODE REVIEW

**Review by Cloud7050 — APPROVED** [review]

**Comment by Cloud7050** [comment]
Curious about the serialisable thing failing test cases. Do you know more?

**Comment by rayshawntan** [comment]
> Curious about the serialisable thing failing test cases. Do you know more?

After trying around, I think I found the reason why it failed. The original implementation of the code called the JSON_STRING_REPRESENTATION directly from the `SerializableTessClass.java`. When I shifted it over, I set it as static in `TestData.java` but I did not import it as static. Instead, I imported the class itself. Will push a new update.

**Review by mamayuan — APPROVED** [review]

**Comment by Cloud7050** [comment]
I'm doing some testing locally as I'm wondering why the difference in imports would cause the tests to fail.

**Comment by Cloud7050** [comment]
I don't think it's an import thing, rather, the copy-paste had a missing `}` at the end of the string.

image

image

image

I think repeating the transfer process just so happened to take human error out of the equation.

**Pull request merged**
